import random
import string
print("Password Generator")
print("-"*10)
cont = input("Make password? (Y/N): " )
if cont == "N":
  print("bye")
  exit()

password_for = input("What is the password for?: ")

password_list = (["a", "b", "c", "d", "e", "f", "g", "h", "i","j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z","1","2" ,"3", "4", "5", "6", "7", "8", "9", "0",])

print("-"*10)
for i in range(100):
  char1 = (random.choice(password_list))
  char2 = (random.choice(password_list))
  char3 = (random.choice(password_list))
  char4 = (random.choice(password_list))
  char5 = (random.choice(password_list))
  char6 = (random.choice(password_list))
  char7 = (random.choice(password_list))
  char8 = (random.choice(password_list))
  char9 = (random.choice(password_list))
  char10 = (random.choice(password_list))
  char11 = (random.choice(password_list))
  char12 = (random.choice(password_list))
  char13 = (random.choice(password_list))
  char14 = (random.choice(password_list))
  char15 = (random.choice(password_list))
  char16 = (random.choice(password_list))
  char17 = (random.choice(password_list))
  char18 = (random.choice(password_list))
  char19 = (random.choice(password_list))
  char20 = (random.choice(password_list))
  char21 = (random.choice(password_list))
  char22 = (random.choice(password_list))
  char23 = (random.choice(password_list))
  char24 = (random.choice(password_list))
  char25 = (random.choice(password_list))
  char26 = (random.choice(password_list))
  char27 = (random.choice(password_list))
  char28 = (random.choice(password_list))
  char29 = (random.choice(password_list))
  char30 = (random.choice(password_list))
  char31 = (random.choice(password_list))
  char32 = (random.choice(password_list))
  char33 = (random.choice(password_list))
  char34 = (random.choice(password_list))
  char35 = (random.choice(password_list))
  char36 = (random.choice(password_list))
  char37 = (random.choice(password_list))
  char38 = (random.choice(password_list))
  char39 = (random.choice(password_list))
  char40 = (random.choice(password_list))
  char41 = (random.choice(password_list))
  char42 = (random.choice(password_list))
  char43 = (random.choice(password_list))
  char44 = (random.choice(password_list))
  char45 = (random.choice(password_list))
  char46 = (random.choice(password_list))
  char47 = (random.choice(password_list))
  char48 = (random.choice(password_list))
  char49 = (random.choice(password_list))
  char50 = (random.choice(password_list))

final_pass = (char1 + char2 + char3 + char4 + char5 + char6 + char7 + char8 + char9 + char10 + char11 + char12 + char13 + char14 + char15 + char16 + char17 + char18 + char19 + char20 + char21 + char22 + char23 + char24 + char25 + char26 + char27 + char28 + char29 + char30 + char31 + char32 + char33 + char34 + char35 + char36 + char37 + char38 + char39 + char40 + char41 + char42 + char43 + char44 + char45 + char46 + char47 + char48 + char49 + char50)

print(final_pass)
print("-"*10)
print("Thank you for using Password Generator")

f = open("pass.txt", "a")
f.write("Site:" + password_for +"    " +  "Password:"  + final_pass + '\n')
print("Password saved successfully.")